package org.kmymoney.apiext.trxmgr;

import java.util.Arrays;

import org.apache.commons.text.StringEscapeUtils;
import org.kmymoney.api.read.KMyMoneyTransaction;
import org.kmymoney.api.read.KMyMoneyTransactionSplit;
import org.kmymoney.api.write.KMyMoneyWritableFile;
import org.kmymoney.api.write.KMyMoneyWritableTransaction;
import org.kmymoney.api.write.KMyMoneyWritableTransactionSplit;
import org.kmymoney.api.write.impl.KMyMoneyWritableTransactionSplitImpl;
import org.kmymoney.base.basetypes.complex.KMMQualifSpltID;
import org.kmymoney.base.basetypes.simple.KMMTrxID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TransactionMergerVar3 extends TransactionMergerBase
								   implements IFTransactionMerger 
{

	// Logger
    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionMergerVar3.class);
    
    // ---------------------------------------------------------------
    // ::MAGIC
    
	private static final String DOCTYPE_MATCH       = "<!DOCTYPE MATCH>";
	private static final String CONTAINER_OPEN_TAG  = "<CONTAINER>";
    private static final String CONTAINER_CLOSE_TAG = "</CONTAINER>";

	private static final String OPEN_BRACKET_CODE   = "&#60;";
	private static final String CLOSE_BRACKET_CODE  = "&#10;";
	
	// ----------------------------

	static final String KMM_MATCHED_TX          = "kmm-matched-tx";
	static final String KMM_MATCH_SPLIT         = "kmm-match-split";
	
	static final String KMM_ORIG_POSTDATE       = "kmm-orig-postdate";
	static final String KMM_ORIG_PAYEE          = "kmm-orig-payee";
	static final String KMM_ORIG_MEMO           = "kmm-orig-memo";
	static final String KMM_ORIG_ONE_SPLIT      = "kmm-orig-onesplit";
	static final String KMM_ORIG_NOT_RECONCILED = "kmm-orig-not-reconciled";

    // ---------------------------------------------------------------
    
	// CAUTION: 
	// In this merger variant, the survivor trx's bank split will be deleted
	// and vice versa.
	// ==> The zdTrxBankSpltID (ZD Splt), part of the dier trx, will die, 
	//     but a copy of it will survive as part of the survivor trx, 
	//     called ZS Splt/after.
        //
	// Visualization of Typical Example:
	// ---------------------------------
	//
	// Dier Trx                            Survivor Trx
        // (imported from bank)                (generated by JKMyMoneyLib)
	// |                                   +-- XS Splt (to stock account)
	// |                                   +-- YS.a Splt (to expenses account)
	// |                                   +-- YS.b Splt (to expenses account)
	// |                                   +-- YS.c Splt (to income account)
	// +-- ZD Splt (to bank acct)          +-- ZS Splt/before (to bank account)
	//     ^                               |   ^
	//     +-- will be copied to           |   +-- Will be replaced by ZS Splt/after
	//         survivor trx -------------> +-- ZS Splt/after (to bank account)
	//                                         ^
	//                                         +-- Copy of ZD Splt
        //
	// Notice the the dier trx is not sane/balanced; it consists of one
        // single split. However, it might be marked as reconciled.
	// 
	// Let that sink in for a moment before you review the code in this class.

	private KMyMoneyWritableTransaction survTrx = null;
	private KMyMoneyWritableTransaction dierTrx = null;
	
	private KMyMoneyTransactionSplit zDierTrxBankSplt = null; // "ZS Split/before"
	private KMyMoneyTransactionSplit zSurvTrxBankSpltBefore = null; // "ZS Split/before"
	
	private KMMQualifSpltID zDierTrxBankSpltID = null;       // cf. above
	private KMMQualifSpltID zSurvTrxBankSpltBeforeID = null; // dto.
	
	private boolean postDateFromDierTrx = false;

    // ---------------------------------------------------------------
	
	public TransactionMergerVar3(KMyMoneyWritableFile kmmFile) {
		super(kmmFile);
		setVar(Var.VAR_3);
	}
    
    // ---------------------------------------------------------------
	
	public KMMQualifSpltID getZDierTrxBankSpltID() {
		return zDierTrxBankSpltID;
	}
    
	public void setZDierTrxBankSpltID(KMMQualifSpltID spltID) {
		this.zDierTrxBankSpltID = spltID;
		
		zDierTrxBankSplt = kmmFile.getTransactionSplitByID(spltID);
	}
	
	// ---
    
	public KMMQualifSpltID getZSurvTrxBankSpltBeforeID() {
		return zSurvTrxBankSpltBeforeID;
	}
    
	public void setZSurvTrxBankSpltBeforeID(KMMQualifSpltID spltID) {
		this.zSurvTrxBankSpltBeforeID = spltID;
		
		zSurvTrxBankSpltBefore = kmmFile.getTransactionSplitByID(spltID);
	}
    
	// ---
    
	public KMyMoneyWritableTransaction getSurvTrx() {
		return survTrx;
	}
    
	public void setSurvTrx(KMyMoneyWritableTransaction trx) {
		this.survTrx = trx;
	}
    
	public KMyMoneyWritableTransaction getDierTrx() {
		return dierTrx;
	}
    
	public void setDierTrx(KMyMoneyWritableTransaction trx) {
		this.dierTrx = trx;
	}
    
	// ---
	
	public boolean isPostDateFromDierTrxSet() {
		return postDateFromDierTrx;
	}
    
	public void setPostDateFromDierTrx(boolean val) {
		postDateFromDierTrx = val;
	}
    
    // ---------------------------------------------------------------
    
	@Override
	public void merge(KMMTrxID survivorID, KMMTrxID dierID) throws MergePlausiCheckException {
		KMyMoneyWritableTransaction survivor = kmmFile.getWritableTransactionByID(survivorID);
		KMyMoneyWritableTransaction dier = kmmFile.getWritableTransactionByID(dierID);
		merge(survivor, dier);
	}

	@Override
	public void merge(KMyMoneyWritableTransaction survivor, KMyMoneyWritableTransaction dier) throws MergePlausiCheckException {
		if ( survivor == null ) {
			throw new IllegalArgumentException("argument <survivor> is null");
		}
		
		if ( ! survivor.getID().isSet() ) {
			throw new IllegalArgumentException("argument <survivor>'s ID is not set");
		}
		
		if ( dier == null ) {
			throw new IllegalArgumentException("argument <dier> is null");
		}
		
		if ( ! dier.getID().isSet() ) {
			throw new IllegalArgumentException("argument <dier>'s ID is not set");
		}
		
		// ---
		
		setSurvTrx(survivor);
		setDierTrx(dier);
		
		// ---
		
		if ( zDierTrxBankSpltID == null ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is null");
		}
		
		if ( zSurvTrxBankSpltBeforeID == null ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is null");
		}
		
		if ( ! zDierTrxBankSpltID.isSet() ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is not set");
		}
		
		if ( ! zSurvTrxBankSpltBeforeID.isSet() ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is not set");
		}
		
		if ( zDierTrxBankSpltID.equals(zSurvTrxBankSpltBeforeID) ) {
			throw new IllegalStateException("IDs of Z dier Trx bank Split and Z survivor Trx bank Split (before) are identical");
		}
		
		// ---
		
		// 1) Perform plausi checks
		if ( plausiCheck(survivor, dier) ) {
			LOGGER.info("merge: survivor-dier-pair passed plausi check: " + survivor.getID() + "/" + dier.getID());
		} else {
			LOGGER.error("merge: survivor-dier-pair did not pass plausi check: " + survivor.getID() + "/" + dier.getID());
			throw new MergePlausiCheckException();
		}

		KMyMoneyWritableTransactionSplit zSurvBankTrxSpltAfter = copyBankTrxSplt();
		LOGGER.info("merge: Transaction Split " + zDierTrxBankSpltID + " copied to new Splt " + zSurvBankTrxSpltAfter.getID());
		
		KMyMoneyWritableTransactionSplit zSurvBankTrxSpltBefore = kmmFile.getWritableTransactionSplitByID(zSurvTrxBankSpltBeforeID);
		survTrx.removeSplit(zSurvBankTrxSpltBefore);
		LOGGER.info("merge: Removed Transaction Split " + zSurvTrxBankSpltBeforeID);
		
		// Sic: Because in KMyMoney, the split-IDs have semantics, and KMyMoney would not 
		// handle the whole transaction as expected when the split no. S0001 
		// (often zSurvTrxBankSpltBefore's ID) is missing.
		// Not so in the sister project.
		// Call the "secret" method written for this particular case only
		// (and not to be used anywhere else!)
		((KMyMoneyWritableTransactionSplitImpl) zSurvBankTrxSpltAfter).replaceID(zSurvTrxBankSpltBeforeID.getSplitID());
		
		KMMTrxID dierID = dier.getID();
		kmmFile.removeTransaction(dier);
		LOGGER.info("merge: Transaction " + dierID + " (dier) removed");
	}

    // ---------------------------------------------------------------
	
	// ::MAGIC
	static String getDierKMMContainerString(final KMyMoneyTransaction trx, final boolean removeID) {
		String result = DOCTYPE_MATCH;
		result += CONTAINER_OPEN_TAG;
		result += getDierKMMXMLString(trx, removeID);
		result += CONTAINER_CLOSE_TAG;
		
		return result;
	}

	// ::MAGIC
	private static String getDierKMMXMLString(final KMyMoneyTransaction trx, final boolean removeID) {
		String origStr = trx.toXMLString(); // multi-line string; first line is XML header
		String[] lines = origStr.split("\n");
		
		if ( removeID )
			lines[1] = lines[1].replaceAll("id=\"T[0-9]*\"", "id=\"\""); // remove trx ID from second line
		
		String result = String.join("\n", Arrays.copyOfRange(lines, 1, lines.length)); // remove first line (XML header)
		result = result.replace("\n", ""); // remove all other newline chars
		
		return result;
	}

	// ::MAGIC
	static String getDierKMMContainerEscapedString(final KMyMoneyTransaction trx, final boolean removeID) {
		String result = getDierKMMContainerString(trx, removeID);
		
		// 1) The part that I (more or less) understand.
		//    Notice that there are two "layers" of encoding "<" and ">".
		result = result
					.replaceAll("<", OPEN_BRACKET_CODE)
					.replaceAll(">", ">" + CLOSE_BRACKET_CODE); // sic: notice asymmetry
		result = StringEscapeUtils.escapeXml11(result);
		
		// 2) Now some magic that I don't understand.
		//    Very ugly, but it works.
		result = result.replaceAll("&gt;&amp;#10;", "&gt;" + CLOSE_BRACKET_CODE); // make asymmetry from above even worse
		result = CLOSE_BRACKET_CODE + result; // add s.t. to beginning of string (and yes, it's a *closing* code!)
		result = result.replaceAll(";" + CLOSE_BRACKET_CODE + "$", ";"); // remove s.t. from end of string 
		
		return result;
	}

    // ---------------------------------------------------------------
	
	private KMyMoneyWritableTransactionSplit copyBankTrxSplt() {
		boolean origOneSplit = ( survTrx.getSplitsCount() == 1 ); // *Before* copy is generated
		
		KMyMoneyWritableTransactionSplit copy = survTrx.createWritableSplit(zDierTrxBankSplt.getAccount());

		// ---
		
		copy.addUserDefinedAttribute(KMM_MATCH_SPLIT, zDierTrxBankSplt.getID().toString());
		copy.addUserDefinedAttribute(KMM_MATCHED_TX, getDierKMMContainerEscapedString(dierTrx, true));
		
		// ---
		
		if ( zDierTrxBankSplt.getAction() != null ) {
			copy.setAction( zDierTrxBankSplt.getAction() );
		} else {
			// if ( copy.getAction() != null ) { // unnecessary
				copy.unsetAction();
			// }
		}
		
		// ---
		
		copy.setAccountID( zSurvTrxBankSpltBefore.getAccountID() );
		
		// ---
		
		copy.setValue( zDierTrxBankSplt.getValueRat() );
		copy.setShares( zDierTrxBankSplt.getSharesRat() );
		
		// ---
		
		if ( zDierTrxBankSplt.getNumber() != null ) {
			copy.setNumber( zDierTrxBankSplt.getNumber() );
		}

		// ---
		
		if ( zDierTrxBankSplt.getBankID() != null ) {
			copy.setBankID( zDierTrxBankSplt.getBankID() );
		}

		// ---

		// This flag is always set in KMyMoney for merging.
		// We just want to be able to set it explicitly.
		if ( postDateFromDierTrx ) {
			copy.addUserDefinedAttribute(KMM_ORIG_POSTDATE, survTrx.getDatePosted().toString() );
			survTrx.setDatePosted( dierTrx.getDatePosted() );
		}

		// ---
		
		if ( zSurvTrxBankSpltBefore.getPayeeID() != null ) {
			copy.addUserDefinedAttribute(KMM_ORIG_PAYEE, zSurvTrxBankSpltBefore.getPayeeID().toString());
		} else {
			copy.addUserDefinedAttribute(KMM_ORIG_PAYEE, "dummy");
			((KMyMoneyWritableTransactionSplitImpl) copy).setUserDefinedAttribute(KMM_ORIG_PAYEE, "", true);
		}
		
		if ( zDierTrxBankSplt.getPayeeID() != null ) {
			copy.setPayeeID( zDierTrxBankSplt.getPayeeID() );
		} else {
			if ( copy.getPayeeID() != null ) { // sic, necessary
				copy.unsetPayeeID();
			}
		}
		
		// ---
		
		if ( zSurvTrxBankSpltBefore.getMemo() != null ) {
			copy.addUserDefinedAttribute(KMM_ORIG_MEMO, zSurvTrxBankSpltBefore.getMemo());
		} else {
			copy.addUserDefinedAttribute(KMM_ORIG_MEMO, "dummy");
			((KMyMoneyWritableTransactionSplitImpl) copy).setUserDefinedAttribute(KMM_ORIG_MEMO, "", true);
		}
		
		if ( zDierTrxBankSplt.getMemo() != null ) {
			copy.setMemo( zDierTrxBankSplt.getMemo() );
		} else {
			copy.setMemo("");
		}
		
		// ---
		
		if ( origOneSplit ) {
			copy.addUserDefinedAttribute(KMM_ORIG_ONE_SPLIT, "yes");
//		} else {
			// Actually; in the other case, no "no" is generated,
			// but the property is simply not set. That's how
			// KMyMoney does it.
//			copy.addUserDefinedAttribute(KMM_ORIG_ONE_SPLIT, "no");
		}
		
		// ---
		
		if ( zSurvTrxBankSpltBefore.getReconState() != null ) {
			if ( zSurvTrxBankSpltBefore.getReconState() != KMyMoneyTransactionSplit.ReconState.RECONCILED ) {
				copy.addUserDefinedAttribute(KMM_ORIG_NOT_RECONCILED, "yes"); // sic, *not* reconciled
			} else {
				// Actually; in the other case, no "no" is generated,
				// but the property is simply not set. That's how
				// KMyMoney does it.
				copy.addUserDefinedAttribute(KMM_ORIG_NOT_RECONCILED, "no"); // cf. above
			}
		} else {
			// Should not happen -- just in case
			copy.addUserDefinedAttribute(KMM_ORIG_NOT_RECONCILED, "yes");
		}
		
		if ( zDierTrxBankSplt.getReconState() != null ) {
			copy.setReconState( zDierTrxBankSplt.getReconState() );
		} else {
			copy.setReconState( KMyMoneyTransactionSplit.ReconState.NOT_RECONCILED );
		}
		
		// ---
		
		if ( zDierTrxBankSplt.getUserDefinedAttributeKeys() != null ) {
			for ( String attrKey : zDierTrxBankSplt.getUserDefinedAttributeKeys() ) {
				if ( copy.getUserDefinedAttributeKeys() != null ) {
					if ( copy.getUserDefinedAttributeKeys().contains(attrKey) ) {
						copy.setUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
					} else {
						copy.addUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
					}
				} else {
					copy.addUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
				}
			} // for
		}
		
		return copy;
	}

}
