package org.kmymoney.apiext.trxmgr;

import java.util.Arrays;

import org.apache.commons.text.StringEscapeUtils;
import org.kmymoney.api.read.KMyMoneyTransaction;
import org.kmymoney.api.read.KMyMoneyTransactionSplit;
import org.kmymoney.api.write.KMyMoneyWritableFile;
import org.kmymoney.api.write.KMyMoneyWritableTransaction;
import org.kmymoney.api.write.KMyMoneyWritableTransactionSplit;
import org.kmymoney.api.write.impl.KMyMoneyWritableTransactionSplitImpl;
import org.kmymoney.base.basetypes.complex.KMMQualifSpltID;
import org.kmymoney.base.basetypes.simple.KMMTrxID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TransactionMergerVar3 extends TransactionMergerBase
								   implements IFTransactionMerger 
{
    // Logger
    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionMergerVar3.class);
    
    // ---------------------------------------------------------------
    
	// CAUTION: 
	// In this merger variant, the survivor trx's bank split will be deleted
	// and vice versa.
	// ==> The zdTrxBankSpltID (ZD Splt), part of the dier trx, will die, 
	//     but a copy of it will survive as part of the survivor trx, 
	//     called ZS Splt/after.
        //
	// Visualization of Typical Example:
	// ---------------------------------
	//
	// Dier Trx                            Survivor Trx
        // (imported from bank)                (generated by JKMyMoneyLib)
	// |                                   +-- XS Splt (to stock account)
	// |                                   +-- YS.a Splt (to expenses account)
	// |                                   +-- YS.b Splt (to expenses account)
	// |                                   +-- YS.c Splt (to income account)
	// +-- ZD Splt (to bank acct)          +-- ZS Splt/before (to bank account)
	//     ^                               |   ^
	//     +-- will be copied to           |   +-- Will be replaced by ZS Splt/after
	//         survivor trx -------------> +-- ZS Splt/after (to bank account)
	//                                         ^
	//                                         +-- Copy of ZD Splt
        //
	// Notice the the dier trx is not sane/balanced; it consists of one
        // single split. However, it might be marked as reconciled.
	// 
	// Let that sink in for a moment before you review the code in this class.

	private KMyMoneyWritableTransaction survTrx = null;
	private KMyMoneyWritableTransaction dierTrx = null;
	
	private KMyMoneyTransactionSplit zDierTrxBankSplt = null; // "ZS Split/before"
	private KMyMoneyTransactionSplit zSurvTrxBankSpltBefore = null; // "ZS Split/before"
	
	private KMMQualifSpltID zDierTrxBankSpltID = null;       // cf. above
	private KMMQualifSpltID zSurvTrxBankSpltBeforeID = null; // dto.

    // ---------------------------------------------------------------
	
	public TransactionMergerVar3(KMyMoneyWritableFile kmmFile) {
		super(kmmFile);
		setVar(Var.VAR_3);
	}
    
    // ---------------------------------------------------------------
	
	public KMMQualifSpltID getZDierTrxBankSpltID() {
		return zDierTrxBankSpltID;
	}
    
	public void setZDierTrxBankSpltID(KMMQualifSpltID spltID) {
		this.zDierTrxBankSpltID = spltID;
		
		zDierTrxBankSplt = kmmFile.getTransactionSplitByID(spltID);
	}
	
	// ---
    
	public KMMQualifSpltID getZSurvTrxBankSpltBeforeID() {
		return zSurvTrxBankSpltBeforeID;
	}
    
	public void setZSurvTrxBankSpltBeforeID(KMMQualifSpltID spltID) {
		this.zSurvTrxBankSpltBeforeID = spltID;
		
		zSurvTrxBankSpltBefore = kmmFile.getTransactionSplitByID(spltID);
	}
    
	// ---
    
	public KMyMoneyWritableTransaction getSurvTrx() {
		return survTrx;
	}
    
	public void setSurvTrx(KMyMoneyWritableTransaction trx) {
		this.survTrx = trx;
	}
    
	public KMyMoneyWritableTransaction getDierTrx() {
		return dierTrx;
	}
    
	public void setDierTrx(KMyMoneyWritableTransaction trx) {
		this.dierTrx = trx;
	}
    
    // ---------------------------------------------------------------
    
	@Override
	public void merge(KMMTrxID survivorID, KMMTrxID dierID) throws MergePlausiCheckException {
		KMyMoneyWritableTransaction survivor = kmmFile.getWritableTransactionByID(survivorID);
		KMyMoneyWritableTransaction dier = kmmFile.getWritableTransactionByID(dierID);
		merge(survivor, dier);
	}

	@Override
	public void merge(KMyMoneyWritableTransaction survivor, KMyMoneyWritableTransaction dier) throws MergePlausiCheckException {
		if ( survivor == null ) {
			throw new IllegalArgumentException("argument <survivor> is null");
		}
		
		if ( ! survivor.getID().isSet() ) {
			throw new IllegalArgumentException("argument <survivor>'s ID is not set");
		}
		
		if ( dier == null ) {
			throw new IllegalArgumentException("argument <dier> is null");
		}
		
		if ( ! dier.getID().isSet() ) {
			throw new IllegalArgumentException("argument <dier>'s ID is not set");
		}
		
		// ---
		
		setSurvTrx(survivor);
		setDierTrx(dier);
		
		// ---
		
		if ( zDierTrxBankSpltID == null ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is null");
		}
		
		if ( zSurvTrxBankSpltBeforeID == null ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is null");
		}
		
		if ( ! zDierTrxBankSpltID.isSet() ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is not set");
		}
		
		if ( ! zSurvTrxBankSpltBeforeID.isSet() ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is not set");
		}
		
		if ( zDierTrxBankSpltID.equals(zSurvTrxBankSpltBeforeID) ) {
			throw new IllegalStateException("IDs of Z dier Trx bank Split and Z survivor Trx bank Split (before) are identical");
		}
		
		// ---
		
		// 1) Perform plausi checks
		if ( plausiCheck(survivor, dier) ) {
			LOGGER.info("merge: survivor-dier-pair passed plausi check: " + survivor.getID() + "/" + dier.getID());
		} else {
			LOGGER.error("merge: survivor-dier-pair did not pass plausi check: " + survivor.getID() + "/" + dier.getID());
			throw new MergePlausiCheckException();
		}

		KMyMoneyWritableTransactionSplit zSurvBankTrxSpltAfter = copyBankTrxSplt();
		LOGGER.info("merge: Transaction Split " + zDierTrxBankSpltID + " copied to new Splt " + zSurvBankTrxSpltAfter.getID());
		
		KMyMoneyWritableTransactionSplit zSurvBankTrxSpltBefore = kmmFile.getWritableTransactionSplitByID(zSurvTrxBankSpltBeforeID);
		survTrx.remove(zSurvBankTrxSpltBefore);
		LOGGER.info("merge: Removed Transaction Split " + zSurvTrxBankSpltBeforeID);
		
		// Sic: Because in KMyMoney, the split-IDs have semantics, and KMyMoney would not 
		// handle the whole transaction as expected when the split no. S0001 
		// (often zSurvTrxBankSpltBefore's ID) is missing.
		// Not so in the sister project.
		// Call the "secret" method written for this particular case only
		// (and not to be used anywhere else!)
		((KMyMoneyWritableTransactionSplitImpl) zSurvBankTrxSpltAfter).replaceID(zSurvTrxBankSpltBeforeID.getSplitID());

		KMMTrxID dierID = dier.getID();
		kmmFile.removeTransaction(dier);
		LOGGER.info("merge: Transaction " + dierID + " (dier) removed");
	}

    // ---------------------------------------------------------------
	
	// ::MAGIC
	static String getDierKMMContainerString(final KMyMoneyTransaction trx, final boolean removeID) {
		String result = "<!DOCTYPE MATCH>";
		result += "<CONTAINER>";
		result += getDierKMMXMLString(trx, removeID);
		result += "</CONTAINER>";
		
		return result;
	}

	// ::MAGIC
	private static String getDierKMMXMLString(final KMyMoneyTransaction trx, final boolean removeID) {
		String origStr = trx.toXMLString(); // multi-line string
		String[] lines = origStr.split("\n");
		
		if ( removeID )
			lines[1] = lines[1].replaceAll("id=\"T[0-9]*\"", "id=\"\""); // remove trx ID from second line
		
		String result = String.join("\n", Arrays.copyOfRange(lines, 1, lines.length)); // remove first line
		result = result.replace("\n", ""); // remove all other newline chars
		
		return result;
	}

	// ::MAGIC
	static String getDierKMMContainerEscapedString(final KMyMoneyTransaction trx, final boolean removeID) {
		String result = getDierKMMContainerString(trx, removeID);
		result = result.replaceAll("<", "&#60;").replaceAll(">", ">&#10;"); // sic
		result = StringEscapeUtils.escapeXml11(result);
		result = result.replaceAll("&gt;&amp;#10;", "&gt;&#10;"); // sic
		result = "&#10;" + result; // sic
		result = result.replaceAll(";&#10;$", ";"); // sic
		
		return result;
	}

    // ---------------------------------------------------------------
	
	private KMyMoneyWritableTransactionSplit copyBankTrxSplt() {
		KMyMoneyWritableTransactionSplit copy = survTrx.createWritableSplit(zDierTrxBankSplt.getAccount());

		copy.addUserDefinedAttribute("kmm-matched-tx", getDierKMMContainerEscapedString(dierTrx, true));
		copy.addUserDefinedAttribute("kmm-match-split", zDierTrxBankSplt.getID().toString());
		
		if ( zDierTrxBankSplt.getAction() != null )
			copy.setAction(zDierTrxBankSplt.getAction());
		
		copy.setAccountID(zSurvTrxBankSpltBefore.getAccountID());
		
		copy.setValue(zDierTrxBankSplt.getValueRat());
		copy.setShares(zDierTrxBankSplt.getSharesRat());
		
		if ( zDierTrxBankSplt.getNumber() != null ) {
			 if ( ! zDierTrxBankSplt.getNumber().isBlank() )
				 copy.setNumber(zDierTrxBankSplt.getNumber());
		}

		if ( zDierTrxBankSplt.getPayee() != null ) {
			copy.addUserDefinedAttribute("kmm-orig-payee", zDierTrxBankSplt.getPayee().toString());
			copy.setPayee(zDierTrxBankSplt.getPayee());
		} else {
			copy.addUserDefinedAttribute("kmm-orig-payee", "dummy"); // ::TOOD
		}
		
		if ( zDierTrxBankSplt.getReconState() != null ) {
			if ( zDierTrxBankSplt.getReconState() == KMyMoneyTransactionSplit.ReconState.RECONCILED )
				copy.addUserDefinedAttribute("kmm-orig-not-reconciled", "no"); // sic, *not* reconciled
			else
				copy.addUserDefinedAttribute("kmm-orig-not-reconciled", "yes"); // cf. above
			copy.setReconState(zDierTrxBankSplt.getReconState());
		} else {
			copy.addUserDefinedAttribute("kmm-orig-not-reconciled", "yes");
		}
		
		if ( zDierTrxBankSplt.getMemo() != null ) {
			if ( ! zDierTrxBankSplt.getMemo().isBlank() ) {
				copy.addUserDefinedAttribute("kmm-orig-memo", zDierTrxBankSplt.getMemo());
				copy.setMemo(zDierTrxBankSplt.getMemo());
			} else {
				copy.addUserDefinedAttribute("kmm-orig-memo", "dummy"); // ::TOOD
			}
		} else {
			copy.addUserDefinedAttribute("kmm-orig-memo", "dummy"); // ::TOOD
		}
		
		// User-defined attributes
		// ::TODO
//		for ( String attrKey : zdTrxBankSplt.getUserDefinedAttributeKeys() ) {
//			newBankTrxSplt.addUserDefinedAttribute( zdTrxBankSplt.getUserDefinedAttribute(attrKey) );
//		}
		
		return copy;
	}

}
