package org.kmymoney.apiext.trxmgr;

import org.kmymoney.api.read.KMyMoneyTransactionSplit;
import org.kmymoney.api.write.KMyMoneyWritableFile;
import org.kmymoney.api.write.KMyMoneyWritableTransaction;
import org.kmymoney.api.write.KMyMoneyWritableTransactionSplit;
import org.kmymoney.api.write.impl.KMyMoneyWritableTransactionSplitImpl;
import org.kmymoney.base.basetypes.complex.KMMQualifSpltID;
import org.kmymoney.base.basetypes.simple.KMMTrxID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TransactionMergerVar2 extends TransactionMergerBase
								   implements IFTransactionMerger 
{
    // Logger
    private static final Logger LOGGER = LoggerFactory.getLogger(TransactionMergerVar2.class);
    
    // ---------------------------------------------------------------
    
	// CAUTION: 
	// In this merger variant, the survivor trx's bank split will be deleted
	// and vice versa.
	// ==> The zdTrxBankSpltID (ZD Splt), part of the dier trx, will die, 
	//     but a copy of it will survive as part of the survivor trx, 
	//     called ZS Splt/after.
        //
	// Visualization of Typical Example:
	// ---------------------------------
	//
	// Dier Trx                            Survivor Trx
        // (imported from bank)                (generated by JKMyMoneyLib)
	// |                                   +-- XS Splt (to stock account)
	// |                                   +-- YS.a Splt (to expenses account)
	// |                                   +-- YS.b Splt (to expenses account)
	// |                                   +-- YS.c Splt (to income account)
	// +-- ZD Splt (to bank acct)          +-- ZS Splt/before (to bank account)
	//     ^                               |   ^
	//     +-- will be copied to           |   +-- Will be replaced by ZS Splt/after
	//         survivor trx -------------> +-- ZS Splt/after (to bank account)
	//                                         ^
	//                                         +-- Copy of ZD Splt
        //
	// Notice the the dier trx is not sane/balanced; it consists of one
        // single split. However, it might be marked as reconciled.
	// 
	// Let that sink in for a moment before you review the code in this class.

	private KMyMoneyWritableTransaction survTrx = null;
	private KMyMoneyWritableTransaction dierTrx = null;
	
	private KMyMoneyTransactionSplit zDierTrxBankSplt = null; // "ZS Split/before"
	private KMyMoneyTransactionSplit zSurvTrxBankSpltBefore = null; // "ZS Split/before"
	
	private KMMQualifSpltID zDierTrxBankSpltID = null;       // cf. above
	private KMMQualifSpltID zSurvTrxBankSpltBeforeID = null; // dto.
	
	private boolean postDateFromDierTrx = false;

    // ---------------------------------------------------------------
	
	public TransactionMergerVar2(KMyMoneyWritableFile kmmFile) {
		super(kmmFile);
		setVar(Var.VAR_2);
	}
    
    // ---------------------------------------------------------------
	
	public KMMQualifSpltID getZDierTrxBankSpltID() {
		return zDierTrxBankSpltID;
	}
    
	public void setZDierTrxBankSpltID(KMMQualifSpltID spltID) {
		this.zDierTrxBankSpltID = spltID;
		
		zDierTrxBankSplt = kmmFile.getTransactionSplitByID(spltID);
	}
	
	// ---
    
	public KMMQualifSpltID getZSurvTrxBankSpltBeforeID() {
		return zSurvTrxBankSpltBeforeID;
	}
    
	public void setZSurvTrxBankSpltBeforeID(KMMQualifSpltID spltID) {
		this.zSurvTrxBankSpltBeforeID = spltID;
		
		zSurvTrxBankSpltBefore = kmmFile.getTransactionSplitByID(spltID);
	}
    
	// ---
    
	public KMyMoneyWritableTransaction getSurvTrx() {
		return survTrx;
	}
    
	public void setSurvTrx(KMyMoneyWritableTransaction trx) {
		this.survTrx = trx;
	}
    
	public KMyMoneyWritableTransaction getDierTrx() {
		return dierTrx;
	}
    
	public void setDierTrx(KMyMoneyWritableTransaction trx) {
		this.dierTrx = trx;
	}
    
	// ---
	
	public boolean isPostDateFromDierTrxSet() {
		return postDateFromDierTrx;
	}
    
	public void setPostDateFromDierTrx(boolean val) {
		postDateFromDierTrx = val;
	}
    
    // ---------------------------------------------------------------
    
	@Override
	public void merge(KMMTrxID survivorID, KMMTrxID dierID) throws MergePlausiCheckException {
		KMyMoneyWritableTransaction survivor = kmmFile.getWritableTransactionByID(survivorID);
		KMyMoneyWritableTransaction dier = kmmFile.getWritableTransactionByID(dierID);
		merge(survivor, dier);
	}

	@Override
	public void merge(KMyMoneyWritableTransaction survivor, KMyMoneyWritableTransaction dier) throws MergePlausiCheckException {
		if ( survivor == null ) {
			throw new IllegalArgumentException("argument <survivor> is null");
		}
		
		if ( ! survivor.getID().isSet() ) {
			throw new IllegalArgumentException("argument <survivor>'s ID is not set");
		}
		
		if ( dier == null ) {
			throw new IllegalArgumentException("argument <dier> is null");
		}
		
		if ( ! dier.getID().isSet() ) {
			throw new IllegalArgumentException("argument <dier>'s ID is not set");
		}
		
		// ---
		
		setSurvTrx(survivor);
		setDierTrx(dier);
		
		// ---
		
		if ( zDierTrxBankSpltID == null ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is null");
		}
		
		if ( zSurvTrxBankSpltBeforeID == null ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is null");
		}
		
		if ( ! zDierTrxBankSpltID.isSet() ) {
			throw new IllegalStateException("Z dier Trx bank Split ID is not set");
		}
		
		if ( ! zSurvTrxBankSpltBeforeID.isSet() ) {
			throw new IllegalStateException("Z survivor Trx bank Split (before) ID is not set");
		}
		
		if ( zDierTrxBankSpltID.equals(zSurvTrxBankSpltBeforeID) ) {
			throw new IllegalStateException("IDs of Z dier Trx bank Split and Z survivor Trx bank Split (before) are identical");
		}
		
		// ---
		
		// 1) Perform plausi checks
		if ( plausiCheck(survivor, dier) ) {
			LOGGER.info("merge: survivor-dier-pair passed plausi check: " + survivor.getID() + "/" + dier.getID());
		} else {
			LOGGER.error("merge: survivor-dier-pair did not pass plausi check: " + survivor.getID() + "/" + dier.getID());
			throw new MergePlausiCheckException();
		}

		KMyMoneyWritableTransactionSplit zSurvBankTrxSpltAfter = copyBankTrxSplt();
		LOGGER.info("merge: Transaction Split " + zDierTrxBankSpltID + " copied to new Splt " + zSurvBankTrxSpltAfter.getID());
		
		KMyMoneyWritableTransactionSplit zSurvBankTrxSpltBefore = kmmFile.getWritableTransactionSplitByID(zSurvTrxBankSpltBeforeID);
		survTrx.removeSplit(zSurvBankTrxSpltBefore);
		LOGGER.info("merge: Removed Transaction Split " + zSurvTrxBankSpltBeforeID);
		
		// Sic: Because in KMyMoney, the split-IDs have semantics, and KMyMoney would not 
		// handle the whole transaction as expected when the split no. S0001 
		// (often zSurvTrxBankSpltBefore's ID) is missing.
		// Not so in the sister project.
		// Call the "secret" method written for this particular case only
		// (and not to be used anywhere else!)
		((KMyMoneyWritableTransactionSplitImpl) zSurvBankTrxSpltAfter).replaceID(zSurvTrxBankSpltBeforeID.getSplitID());
		
		if ( postDateFromDierTrx )
			survTrx.setDatePosted( dierTrx.getDatePosted() );

		KMMTrxID dierID = dier.getID();
		kmmFile.removeTransaction(dier);
		LOGGER.info("merge: Transaction " + dierID + " (dier) removed");
	}

    // ---------------------------------------------------------------
	
	private KMyMoneyWritableTransactionSplit copyBankTrxSplt() {
		KMyMoneyWritableTransactionSplit spltCopy = survTrx.createWritableSplit(zDierTrxBankSplt.getAccount());

		if ( zDierTrxBankSplt.getAction() != null ) {
			spltCopy.setAction(zDierTrxBankSplt.getAction());
		} else {
			spltCopy.unsetAction();
		}
		
		spltCopy.setAccountID(zSurvTrxBankSpltBefore.getAccountID());
		
		spltCopy.setValue(zDierTrxBankSplt.getValueRat());
		spltCopy.setShares(zDierTrxBankSplt.getSharesRat());
		
		if ( zDierTrxBankSplt.getNumber() != null ) {
			spltCopy.setNumber( zDierTrxBankSplt.getNumber() );
		}

		if ( zDierTrxBankSplt.getBankID() != null ) {
			spltCopy.setBankID( zDierTrxBankSplt.getBankID() );
		}

		if ( zDierTrxBankSplt.getPayeeID() != null ) {
			spltCopy.setPayeeID( zDierTrxBankSplt.getPayeeID() );
		} else {
			if ( spltCopy.getPayeeID() != null ) { // sic, necessary
				spltCopy.unsetPayeeID();
			}
		}
		
		if ( zDierTrxBankSplt.getMemo() != null )
			spltCopy.setMemo(zDierTrxBankSplt.getMemo());

		if ( zDierTrxBankSplt.getReconState() != null ) {
			spltCopy.setReconState(zDierTrxBankSplt.getReconState());
		} else {
			spltCopy.setReconState( KMyMoneyTransactionSplit.ReconState.NOT_RECONCILED );
		}
		 
		// ---
		
		if ( zDierTrxBankSplt.getUserDefinedAttributeKeys() != null ) {
			for ( String attrKey : zDierTrxBankSplt.getUserDefinedAttributeKeys() ) {
				if ( spltCopy.getUserDefinedAttributeKeys() != null ) {
					if ( spltCopy.getUserDefinedAttributeKeys().contains(attrKey) ) {
						spltCopy.setUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
					} else {
						spltCopy.addUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
					}
				} else {
					spltCopy.addUserDefinedAttribute( attrKey, zDierTrxBankSplt.getUserDefinedAttribute(attrKey) );
				}
			} // for
		}
		
		return spltCopy;
	}

}
